package uk.gov.hmcts.reform.unspec.enums;

public enum CaseState {
    PENDING_CASE_ISSUED,
    CASE_ISSUED,
    AWAITING_CASE_DETAILS_NOTIFICATION,
    AWAITING_RESPONDENT_ACKNOWLEDGEMENT,
    STAYED,
    AWAITING_APPLICANT_INTENTION,
    CLOSED,
    PROCEEDS_IN_HERITAGE_SYSTEM
}

