package uk.gov.hmcts.reform.unspec.callback;

public enum CaseEvent {
    CREATE_CLAIM,
    CONFIRM_SERVICE,
    REQUEST_EXTENSION,
    RESPOND_EXTENSION,
    MOVE_TO_STAYED,
    ACKNOWLEDGE_SERVICE,
    DEFENDANT_RESPONSE,
    CLAIMANT_RESPONSE,
    WITHDRAW_CLAIM,
    DISCONTINUE_CLAIM,
    NOTIFY_RESPONDENT_SOLICITOR1_FOR_CLAIM_ISSUE,
    NOTIFY_APPLICANT_SOLICITOR1_FOR_REQUEST_FOR_EXTENSION,
    NOTIFY_RESPONDENT_SOLICITOR1_FOR_EXTENSION_RESPONSE,
    NOTIFY_APPLICANT_SOLICITOR1_FOR_SERVICE_ACKNOWLEDGEMENT,
    NOTIFY_APPLICANT_SOLICITOR1_FOR_DEFENDANT_RESPONSE,
    NOTIFY_RESPONDENT_SOLICITOR1_FOR_CASE_HANDED_OFFLINE,
    NOTIFY_APPLICANT_SOLICITOR1_FOR_CASE_HANDED_OFFLINE,
    NOTIFY_RESPONDENT_SOLICITOR1_FOR_CASE_TRANSFERRED_TO_LOCAL_COURT,
    NOTIFY_APPLICANT_SOLICITOR1_FOR_CASE_TRANSFERRED_TO_LOCAL_COURT,
}
