package uk.gov.hmcts.reform.unspec.callback;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum CaseEvent {
    CREATE_CASE("CREATE_CLAIM"),
    CONFIRM_SERVICE("CONFIRM_SERVICE"),
    REQUEST_EXTENSION("REQUEST_EXTENSION"),
    RESPOND_EXTENSION("RESPOND_EXTENSION"),
    MOVE_TO_STAYED("MOVE_TO_STAYED"),
    ACKNOWLEDGE_SERVICE("ACKNOWLEDGE_SERVICE"),
    DEFENDANT_RESPONSE("DEFENDANT_RESPONSE"),
    CLAIMANT_RESPONSE("CLAIMANT_RESPONSE"),
    WITHDRAW_CLAIM("WITHDRAW_CLAIM"),
    DISCONTINUE_CLAIM("DISCONTINUE_CLAIM"),
    SEND_SEALED_CLAIM_EMAIL("SEND_SEALED_CLAIM_EMAIL"),
    GENERATE_SEALED_CLAIM("GENERATE_SEALED_CLAIM"),
    CALCULATE_CLAIM_FEE("CALCULATE_CLAIM_FEE"),
    GENERATE_BPA_PAYMENT("GENERATE_BPA_PAYMENT");

    private final String value;
}
